version: '2'
services:
    client:
        build: .
        volumes:
          - ./package.json:/usr/app/package.json
          - ./package-lock.json:/usr/app/package-lock.json
          - ./src:/usr/app/src
          - ./public:/usr/app/public
          - ./node_modules:/usr/app/node_modules
        ports:
          - "3000:3000"
        stdin_open: true
        command: npm start
